route:
  group_by: ['alertname']
  group_wait: 1m  # timeout for alert set to 1m
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'https://webhook.site/af13aeeb-5914-4ad1-a727-20d35450973e'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
